## Model selection

### Three state-of-the-art algorithms
* Gradient Boosting Clasifier
* Tensorflow Neural Network
* Pythorch Neural Network

In [1]:
import numpy as np
import pandas as pd
import random


from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import StratifiedKFold

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from keras_tuner import RandomSearch

import torch
import torch.nn as nn
import torch.optim as optim


#set random seed
my_seed=42
np.random.seed(my_seed)

In [2]:
# Data set load
data=pd.read_csv('./data/C201905_counterfactuals/simulation_C201905_counterfactuals__ev0.1812.csv',index_col=0)


# Create a target variable, 'delay' and remove unnecessary columns
data['delay']=(data['actual_duration']>data['baseline_duration'])*1
data.drop(columns=['actual_duration','baseline_duration','critical_path'],inplace=True)
# Sort the columns
columns_sorted = sorted(data.columns, key=lambda x: int(x.replace('duration', '')) if 'duration' in x else float('inf'))
data = data[columns_sorted]
data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration9,duration10,duration11,duration12,duration13,duration14,duration15,delay
0,1738.595774,1967.122966,256.504345,2186.408241,1723.181771,1898.648645,1795.289433,1599.760892,2224.382275,2489.048379,2124.279759,139.271436,8.498099,234.542254,7.655393,1
1,1717.864331,1881.352898,266.048082,2324.022291,1849.728508,2083.309016,1839.782891,1593.929687,2323.598219,2279.745524,2334.495021,145.448900,8.235859,238.908956,8.357302,1

In [3]:
# Normalize the dataset to improve the performance of the classifiers

def normalize_dataframe(df, feature_range=(0, 1)):
    """
    Normaliza un DataFrame de pandas utilizando MinMaxScaler.

    Args:
        df (pd.DataFrame): DataFrame a normalizar.
        feature_range (tuple): Rango de valores para la normalización (por defecto (0, 1)).

    Returns:
        pd.DataFrame: DataFrame normalizado.
        MinMaxScaler: Escalador utilizado para la normalización.
    """
    scaler = MinMaxScaler(feature_range=feature_range)
    normalized_data = scaler.fit_transform(df)
    normalized_df = pd.DataFrame(normalized_data, columns=df.columns, index=df.index)
    return normalized_df, scaler

def denormalize_dataframe(normalized_df, scaler):
    """
    Desnormaliza un DataFrame de pandas utilizando un MinMaxScaler previamente ajustado.

    Args:
        normalized_df (pd.DataFrame): DataFrame normalizado.
        scaler (MinMaxScaler): Escalador utilizado para la normalización.

    Returns:
        pd.DataFrame: DataFrame desnormalizado.
    """
    denormalized_data = scaler.inverse_transform(normalized_df)
    denormalized_df = pd.DataFrame(denormalized_data, columns=normalized_df.columns, index=normalized_df.index)
    return denormalized_df


data_to_normalize = data.iloc[:, :-1]  # Select all columns except the last one
normalized_data, my_scaler = normalize_dataframe(data_to_normalize)
data = pd.concat([normalized_data, data.iloc[:, -1]], axis=1)  # Combine normalized data with the last column

data.head(2)

,duration1,duration2,duration3,duration4,duration5,duration6,duration7,duration8,duration9,duration10,duration11,duration12,duration13,duration14,duration15,delay
0,0.751643,0.821171,0.653332,0.547362,0.393468,0.432562,0.715566,0.442461,0.804429,0.891496,0.551165,0.700622,0.641918,0.698465,0.380315,1
1,0.675055,0.594889,0.759338,0.713173,0.582989,0.679778,0.789338,0.432862,0.938094,0.637179,0.819892,0.830761,0.556337,0.752252,0.604439,1

In [4]:
# Split the dataset into features and class
X = data.drop(columns=['delay'])
y = data['delay']

# "stratify=y is used in train_test_split to ensure that the class distribution remains the same in both the training and test sets."
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=my_seed, stratify=y)

# Verify the split
print("Unique labels in training:", np.unique(y_train, return_counts=True))
print("Unique labels in test:", np.unique(y_test, return_counts=True))

Unique labels in training: (array([0, 1]), array([ 5564, 14436]))
Unique labels in test: (array([0, 1]), array([1391, 3609]))

### Gradient Boosting Clasifier

In [5]:
# Results dataframe
results = pd.DataFrame([],columns=['model','kf','Accuracy'])

# Stratified K-Fold cross-validation
kfold =StratifiedKFold(n_splits=5, random_state=my_seed,shuffle=True)

In [6]:
model='GradientBoostingC'
k=0
for train_index, test_index in kfold.split(X,y):

  # parameter optimization in the inner folds
    # n_estimators: number of  boosting stages
    # max_depth of the regression estimators
  mdc = GridSearchCV(GradientBoostingClassifier(),
                    param_grid={"n_estimators": np.linspace(50,200,10).astype('int'),  
                                "max_depth": np.linspace(1,10,5).astype('int')},
                    n_jobs=6)  
  mdc.fit(X.iloc[train_index,:], y.iloc[train_index])
  
  # score of the best model in the outer fold
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
  k+=1

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/1260766298.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/1260766298.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/1260766298.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/1260766298.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))
/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/1260766298.py:15: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, accuracy_score(y.iloc[test_index],mdc.best_estimator_.predict(X.iloc[test_index,:]))]],columns=['model','kf','Accuracy']))

### Tensorflow neural network

In [7]:
def build_model(hp):
    model = keras.Sequential([
        layers.Dense(hp.Int('units', min_value=32, max_value=128, step=32), activation='relu', kernel_regularizer=tf.keras.regularizers.l2(0.01)),
        layers.Dense(2, activation='softmax')
    ])
    model.compile(optimizer=keras.optimizers.Adam(hp.Choice('learning_rate', [0.01, 0.001, 0.0001])),
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])
    return model

model='Tensorflow'
k=0
for train_index, test_index in kfold.split(X,y):

  # parameter optimization in the inner folds
    # units: number of  neurons in the hidden layer
    # learning_rate
  tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=10, executions_per_trial=1, directory='tuner_dir')

  tuner.search(X.iloc[train_index,:], y.iloc[train_index], epochs=30, validation_split=0.2, batch_size=32) 
  best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]
  best_model = tuner.hypermodel.build(best_hps)
  best_model.fit(X.iloc[train_index,:], y.iloc[train_index], epochs=30, batch_size=32, validation_split=0.2, callbacks=[tf.keras.callbacks.EarlyStopping(patience=5, restore_best_weights=True)])
  test_loss, test_acc = best_model.evaluate(X.iloc[test_index,:], y.iloc[test_index])
  
  # score of the best model in the outer fold
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))
  k+=1

Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 560us/step - accuracy: 0.7084 - loss: 0.6897 - val_accuracy: 0.8455 - val_loss: 0.4226
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8411 - loss: 0.4046 - val_accuracy: 0.8393 - val_loss: 0.3644
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.8521 - loss: 0.3579 - val_accuracy: 0.8490 - val_loss: 0.3393
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8621 - loss: 0.3292 - val_accuracy: 0.8640 - val_loss: 0.3299
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8638 - loss: 0.3158 - val_accuracy: 0.8620 - val_loss: 0.3124
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8659 - loss: 0.3118 - val_accuracy: 0.8620 - val_loss: 0.3061
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.8679 - loss: 0.3035 - val_accuracy: 0.8668 - val_loss: 0.2992
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.8761 - loss: 0.2928 - val_accuracy: 0.8710 - val_loss: 0.2910
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.8777 - loss: 0.2899 - val_accuracy: 0.8795 - val_loss: 0.2819
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8888 - loss: 0.2724 - val_accuracy: 0.8988 - val_loss: 0.2667
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 486us/step - accuracy: 0.9029 - loss: 0.2537 - val_accuracy: 0.9045 - val_loss: 0.2413
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9216 - loss: 0.2344 - val_accuracy: 0.9362 - val_loss: 0.2201
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9338 - loss: 0.2164 - val_accuracy: 0.9548 - val_loss: 0.2037
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9408 - loss: 0.2075 - val_accuracy: 0.9588 - val_loss: 0.2047
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9535 - loss: 0.1914 - val_accuracy: 0.9452 - val_loss: 0.1867
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9578 - loss: 0.1833 - val_accuracy: 0.9290 - val_loss: 0.1948
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9587 - loss: 0.1805 - val_accuracy: 0.9693 - val_loss: 0.1719
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9657 - loss: 0.1687 - val_accuracy: 0.9022 - val_loss: 0.2322
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9614 - loss: 0.1689 - val_accuracy: 0.9700 - val_loss: 0.1668
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9634 - loss: 0.1638 - val_accuracy: 0.9607 - val_loss: 0.1566
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9694 - loss: 0.1571 - val_accuracy: 0.9800 - val_loss: 0.1480
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9667 - loss: 0.1541 - val_accuracy: 0.9668 - val_loss: 0.1606
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9681 - loss: 0.1490 - val_accuracy: 0.9672 - val_loss: 0.1537
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9702 - loss: 0.1477 - val_accuracy: 0.9795 - val_loss: 0.1351
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9633 - loss: 0.1518 - val_accuracy: 0.9682 - val_loss: 0.1397
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9704 - loss: 0.1413 - val_accuracy: 0.9783 - val_loss: 0.1359
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9655 - loss: 0.1424 - val_accuracy: 0.9833 - val_loss: 0.1276
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9684 - loss: 0.1399 - val_accuracy: 0.9747 - val_loss: 0.1266
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.9671 - loss: 0.1414 - val_accuracy: 0.9715 - val_loss: 0.1321
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9739 - loss: 0.1348 - val_accuracy: 0.9523 - val_loss: 0.1451
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 350us/step - accuracy: 0.9773 - loss: 0.1268
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/2173360707.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))

500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 619us/step - accuracy: 0.7325 - loss: 0.6633 - val_accuracy: 0.8207 - val_loss: 0.4211
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 495us/step - accuracy: 0.8421 - loss: 0.4029 - val_accuracy: 0.8600 - val_loss: 0.3704
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 498us/step - accuracy: 0.8571 - loss: 0.3468 - val_accuracy: 0.8553 - val_loss: 0.3324
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8672 - loss: 0.3244 - val_accuracy: 0.8577 - val_loss: 0.3590
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8643 - loss: 0.3183 - val_accuracy: 0.8650 - val_loss: 0.3077
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.8738 - loss: 0.3021 - val_accuracy: 0.8677 - val_loss: 0.3035
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8735 - loss: 0.2983 - val_accuracy: 0.8705 - val_loss: 0.2963
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 452us/step - accuracy: 0.8757 - loss: 0.2899 - val_accuracy: 0.8763 - val_loss: 0.3077
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 468us/step - accuracy: 0.8769 - loss: 0.2909 - val_accuracy: 0.8800 - val_loss: 0.2844
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.8887 - loss: 0.2757 - val_accuracy: 0.8890 - val_loss: 0.2690
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8878 - loss: 0.2715 - val_accuracy: 0.9000 - val_loss: 0.2593
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.9030 - loss: 0.2579 - val_accuracy: 0.9078 - val_loss: 0.2450
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9086 - loss: 0.2471 - val_accuracy: 0.9170 - val_loss: 0.2318
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9186 - loss: 0.2320 - val_accuracy: 0.9038 - val_loss: 0.2825
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9246 - loss: 0.2268 - val_accuracy: 0.9317 - val_loss: 0.2105
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9367 - loss: 0.2101 - val_accuracy: 0.9352 - val_loss: 0.2312
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9424 - loss: 0.2017 - val_accuracy: 0.9553 - val_loss: 0.1917
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9523 - loss: 0.1890 - val_accuracy: 0.9225 - val_loss: 0.2058
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 442us/step - accuracy: 0.9504 - loss: 0.1881 - val_accuracy: 0.9647 - val_loss: 0.1824
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9528 - loss: 0.1830 - val_accuracy: 0.9643 - val_loss: 0.1734
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9534 - loss: 0.1809 - val_accuracy: 0.9592 - val_loss: 0.1834
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9594 - loss: 0.1704 - val_accuracy: 0.9703 - val_loss: 0.1613
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.9593 - loss: 0.1682 - val_accuracy: 0.9640 - val_loss: 0.1725
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9633 - loss: 0.1659 - val_accuracy: 0.9655 - val_loss: 0.1556
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.9643 - loss: 0.1630 - val_accuracy: 0.9778 - val_loss: 0.1504
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9674 - loss: 0.1524 - val_accuracy: 0.9762 - val_loss: 0.1475
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9697 - loss: 0.1536 - val_accuracy: 0.9643 - val_loss: 0.1621
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9642 - loss: 0.1551 - val_accuracy: 0.9822 - val_loss: 0.1422
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9683 - loss: 0.1478 - val_accuracy: 0.9822 - val_loss: 0.1414
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9697 - loss: 0.1483 - val_accuracy: 0.9722 - val_loss: 0.1395
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 406us/step - accuracy: 0.9633 - loss: 0.1535
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/2173360707.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))

500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 552us/step - accuracy: 0.7401 - loss: 0.6466 - val_accuracy: 0.8503 - val_loss: 0.4447
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8357 - loss: 0.4076 - val_accuracy: 0.8687 - val_loss: 0.3613
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.8577 - loss: 0.3539 - val_accuracy: 0.8727 - val_loss: 0.3268
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8606 - loss: 0.3339 - val_accuracy: 0.8668 - val_loss: 0.3118
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8608 - loss: 0.3227 - val_accuracy: 0.8770 - val_loss: 0.2977
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8716 - loss: 0.3059 - val_accuracy: 0.8765 - val_loss: 0.3183
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.8758 - loss: 0.2959 - val_accuracy: 0.8848 - val_loss: 0.2926
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.8757 - loss: 0.2954 - val_accuracy: 0.8957 - val_loss: 0.2639
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8969 - loss: 0.2698 - val_accuracy: 0.9062 - val_loss: 0.2462
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9022 - loss: 0.2571 - val_accuracy: 0.9268 - val_loss: 0.2367
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9199 - loss: 0.2359 - val_accuracy: 0.9445 - val_loss: 0.2229
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9361 - loss: 0.2196 - val_accuracy: 0.9430 - val_loss: 0.1994
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9429 - loss: 0.2058 - val_accuracy: 0.9600 - val_loss: 0.2042
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9509 - loss: 0.1983 - val_accuracy: 0.9585 - val_loss: 0.1814
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9496 - loss: 0.1944 - val_accuracy: 0.9703 - val_loss: 0.1781
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9526 - loss: 0.1872 - val_accuracy: 0.9690 - val_loss: 0.1659
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9581 - loss: 0.1776 - val_accuracy: 0.9690 - val_loss: 0.1692
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.9641 - loss: 0.1707 - val_accuracy: 0.9690 - val_loss: 0.1573
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9693 - loss: 0.1612 - val_accuracy: 0.9038 - val_loss: 0.2349
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9640 - loss: 0.1650 - val_accuracy: 0.9778 - val_loss: 0.1480
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9640 - loss: 0.1626 - val_accuracy: 0.9488 - val_loss: 0.1621
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9633 - loss: 0.1561 - val_accuracy: 0.9793 - val_loss: 0.1416
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9648 - loss: 0.1553 - val_accuracy: 0.9762 - val_loss: 0.1382
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9735 - loss: 0.1459 - val_accuracy: 0.9753 - val_loss: 0.1349
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9667 - loss: 0.1476 - val_accuracy: 0.9712 - val_loss: 0.1358
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 439us/step - accuracy: 0.9706 - loss: 0.1436 - val_accuracy: 0.9707 - val_loss: 0.1365
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9718 - loss: 0.1411 - val_accuracy: 0.9682 - val_loss: 0.1335
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 425us/step - accuracy: 0.9691 - loss: 0.1412 - val_accuracy: 0.9630 - val_loss: 0.1433
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 427us/step - accuracy: 0.9624 - loss: 0.1467 - val_accuracy: 0.9775 - val_loss: 0.1296
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 484us/step - accuracy: 0.9710 - loss: 0.1344 - val_accuracy: 0.9843 - val_loss: 0.1252
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 353us/step - accuracy: 0.9860 - loss: 0.1229
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/2173360707.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))

500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 671us/step - accuracy: 0.7339 - loss: 0.6723 - val_accuracy: 0.8460 - val_loss: 0.4213
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8373 - loss: 0.4115 - val_accuracy: 0.8615 - val_loss: 0.3642
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8591 - loss: 0.3595 - val_accuracy: 0.8695 - val_loss: 0.3386
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 441us/step - accuracy: 0.8600 - loss: 0.3402 - val_accuracy: 0.8665 - val_loss: 0.3191
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 454us/step - accuracy: 0.8649 - loss: 0.3192 - val_accuracy: 0.8633 - val_loss: 0.3469
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.8630 - loss: 0.3201 - val_accuracy: 0.8615 - val_loss: 0.3136
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8714 - loss: 0.3051 - val_accuracy: 0.8662 - val_loss: 0.3013
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8686 - loss: 0.3032 - val_accuracy: 0.8668 - val_loss: 0.3038
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.8691 - loss: 0.3052 - val_accuracy: 0.8727 - val_loss: 0.3087
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8736 - loss: 0.2915 - val_accuracy: 0.8712 - val_loss: 0.3189
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 443us/step - accuracy: 0.8787 - loss: 0.2854 - val_accuracy: 0.8880 - val_loss: 0.2766
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 444us/step - accuracy: 0.8886 - loss: 0.2752 - val_accuracy: 0.8928 - val_loss: 0.2566
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9019 - loss: 0.2559 - val_accuracy: 0.9055 - val_loss: 0.2376
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9151 - loss: 0.2378 - val_accuracy: 0.9337 - val_loss: 0.2210
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9335 - loss: 0.2198 - val_accuracy: 0.9485 - val_loss: 0.2060
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9402 - loss: 0.2086 - val_accuracy: 0.9572 - val_loss: 0.1947
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9487 - loss: 0.1956 - val_accuracy: 0.9520 - val_loss: 0.1834
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 429us/step - accuracy: 0.9482 - loss: 0.1957 - val_accuracy: 0.9550 - val_loss: 0.1964
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 436us/step - accuracy: 0.9558 - loss: 0.1846 - val_accuracy: 0.9542 - val_loss: 0.1717
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9533 - loss: 0.1816 - val_accuracy: 0.9730 - val_loss: 0.1650
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9542 - loss: 0.1824 - val_accuracy: 0.9745 - val_loss: 0.1589
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.9609 - loss: 0.1713 - val_accuracy: 0.9675 - val_loss: 0.1551
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9641 - loss: 0.1638 - val_accuracy: 0.9392 - val_loss: 0.1697
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 438us/step - accuracy: 0.9708 - loss: 0.1556 - val_accuracy: 0.9775 - val_loss: 0.1469
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 489us/step - accuracy: 0.9625 - loss: 0.1572 - val_accuracy: 0.9778 - val_loss: 0.1429
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9655 - loss: 0.1564 - val_accuracy: 0.9772 - val_loss: 0.1395
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9694 - loss: 0.1504 - val_accuracy: 0.9465 - val_loss: 0.1571
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 449us/step - accuracy: 0.9653 - loss: 0.1507 - val_accuracy: 0.9697 - val_loss: 0.1395
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9689 - loss: 0.1470 - val_accuracy: 0.9490 - val_loss: 0.1532
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 426us/step - accuracy: 0.9725 - loss: 0.1418 - val_accuracy: 0.9685 - val_loss: 0.1331
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 358us/step - accuracy: 0.9742 - loss: 0.1316
Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Epoch 1/30

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/2173360707.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))

500/500 ━━━━━━━━━━━━━━━━━━━━ 1s 550us/step - accuracy: 0.7456 - loss: 0.6526 - val_accuracy: 0.8450 - val_loss: 0.4094
Epoch 2/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 437us/step - accuracy: 0.8456 - loss: 0.3934 - val_accuracy: 0.8660 - val_loss: 0.3569
Epoch 3/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.8617 - loss: 0.3451 - val_accuracy: 0.8658 - val_loss: 0.3289
Epoch 4/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8679 - loss: 0.3194 - val_accuracy: 0.8317 - val_loss: 0.3687
Epoch 5/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.8664 - loss: 0.3143 - val_accuracy: 0.8568 - val_loss: 0.3154
Epoch 6/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.8666 - loss: 0.3120 - val_accuracy: 0.8643 - val_loss: 0.3117
Epoch 7/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.8768 - loss: 0.2952 - val_accuracy: 0.8687 - val_loss: 0.3000
Epoch 8/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.8675 - loss: 0.3036 - val_accuracy: 0.8715 - val_loss: 0.2922
Epoch 9/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 448us/step - accuracy: 0.8822 - loss: 0.2875 - val_accuracy: 0.8823 - val_loss: 0.2756
Epoch 10/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.8947 - loss: 0.2662 - val_accuracy: 0.8925 - val_loss: 0.2598
Epoch 11/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9067 - loss: 0.2487 - val_accuracy: 0.9007 - val_loss: 0.2479
Epoch 12/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9218 - loss: 0.2322 - val_accuracy: 0.9402 - val_loss: 0.2067
Epoch 13/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9376 - loss: 0.2116 - val_accuracy: 0.9525 - val_loss: 0.1996
Epoch 14/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 432us/step - accuracy: 0.9466 - loss: 0.2004 - val_accuracy: 0.9233 - val_loss: 0.2080
Epoch 15/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 440us/step - accuracy: 0.9607 - loss: 0.1858 - val_accuracy: 0.9690 - val_loss: 0.1726
Epoch 16/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 435us/step - accuracy: 0.9556 - loss: 0.1816 - val_accuracy: 0.9588 - val_loss: 0.1706
Epoch 17/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 447us/step - accuracy: 0.9596 - loss: 0.1744 - val_accuracy: 0.9758 - val_loss: 0.1601
Epoch 18/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9636 - loss: 0.1683 - val_accuracy: 0.9475 - val_loss: 0.1709
Epoch 19/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 445us/step - accuracy: 0.9577 - loss: 0.1707 - val_accuracy: 0.9310 - val_loss: 0.1814
Epoch 20/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 490us/step - accuracy: 0.9642 - loss: 0.1582 - val_accuracy: 0.9695 - val_loss: 0.1555
Epoch 21/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9691 - loss: 0.1534 - val_accuracy: 0.9707 - val_loss: 0.1442
Epoch 22/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9707 - loss: 0.1478 - val_accuracy: 0.9785 - val_loss: 0.1381
Epoch 23/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9649 - loss: 0.1513 - val_accuracy: 0.9725 - val_loss: 0.1381
Epoch 24/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.9607 - loss: 0.1540 - val_accuracy: 0.9528 - val_loss: 0.1501
Epoch 25/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 428us/step - accuracy: 0.9644 - loss: 0.1468 - val_accuracy: 0.9810 - val_loss: 0.1330
Epoch 26/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 430us/step - accuracy: 0.9598 - loss: 0.1536 - val_accuracy: 0.9628 - val_loss: 0.1417
Epoch 27/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 433us/step - accuracy: 0.9697 - loss: 0.1376 - val_accuracy: 0.9780 - val_loss: 0.1313
Epoch 28/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 431us/step - accuracy: 0.9689 - loss: 0.1368 - val_accuracy: 0.9615 - val_loss: 0.1389
Epoch 29/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 434us/step - accuracy: 0.9674 - loss: 0.1354 - val_accuracy: 0.9787 - val_loss: 0.1275
Epoch 30/30
500/500 ━━━━━━━━━━━━━━━━━━━━ 0s 446us/step - accuracy: 0.9726 - loss: 0.1308 - val_accuracy: 0.9825 - val_loss: 0.1244
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 359us/step - accuracy: 0.9865 - loss: 0.1222

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/2173360707.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results = results.append( pd.DataFrame([[model,k, test_acc]],columns=['model','kf','Accuracy']))

### Pytorch

In [8]:
# Data preparation

def safe_to_tensor(data_numpy, batch_size=100): # Adjust batch size as needed
    """Convierte arrays NumPy a tensores PyTorch por lotes"""
    if not isinstance(data_numpy, np.ndarray):
        raise ValueError("Input must be a NumPy array")
    
    tensor_parts = []
    for i in range(0, len(data_numpy), batch_size):
        batch = data_numpy[i:i+batch_size]
        tensor_parts.append(torch.from_numpy(batch).float())
    return torch.cat(tensor_parts)


# Convert to tensors
X_train_tensor = safe_to_tensor(X_train.values.astype(np.float32))
X_test_tensor = safe_to_tensor(X_test.values.astype(np.float32))

# Label tensors
y_train_tensor = torch.tensor(y_train.values.astype(np.float32)).unsqueeze(1)
y_test_tensor = torch.tensor(y_test.values.astype(np.float32)).unsqueeze(1)

# Verify tensor shapes
print("Tensors successfully created:")
print(f"X_train_tensor shape: {X_train_tensor.shape}")
print(f"y_train_tensor shape: {y_train_tensor.shape}")

Tensors successfully created:
X_train_tensor shape: torch.Size([20000, 15])
y_train_tensor shape: torch.Size([20000, 1])

In [9]:
# Model definition
class BinaryClassifier(nn.Module):
    def __init__(self, input_dim, hidden_dim=32):
        super(BinaryClassifier, self).__init__()
        self.fc1 = nn.Linear(input_dim, hidden_dim)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_dim, 1)
        self.sigmoid = nn.Sigmoid()  # Capa sigmoide explícita
        
    def forward(self, x):
        x = self.fc1(x)
        x = self.relu(x)
        x = self.fc2(x)
        return self.sigmoid(x)  # Devuelve tensor con sigmoide aplicada
    

# Model instantiation
model = BinaryClassifier(input_dim=X_train.shape[1])
criterion = nn.BCELoss()  # Ahora usamos BCELoss porque aplicamos sigmoide manualmente
optimizer = optim.Adam(model.parameters(), lr=0.001)

In [10]:
# Training loop with memory management
from tqdm import tqdm  # Progress bar

# Definir el tamaño del batch reducido
batch_size = 100  

# 3. Entrenamiento con manejo de memoria y lotes
try:
    model.train()
    for epoch in tqdm(range(30), desc="Entrenando"):
        optimizer.zero_grad()
        
        # Entrenamiento por lotes (batches)
        for i in range(0, len(X_train_tensor), batch_size):
            batch_X = X_train_tensor[i:i + batch_size]
            batch_y = y_train_tensor[i:i + batch_size]

            # Forward pass por lote
            outputs = model(batch_X)
            
            # Verificación de formas
            if outputs.shape != batch_y.shape:
                print(f"Error: outputs shape {outputs.shape} != y shape {batch_y.shape}")
                break

            loss = criterion(outputs, batch_y)
            
            # Backpropagation con manejo de gradientes
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # Evita gradientes explosivos
            optimizer.step()
        
        if (epoch + 1) % 5 == 0:
            print(f'Epoch {epoch + 1}, Loss: {loss.item():.4f}')
            
except RuntimeError as e:
    print(f"Error durante el entrenamiento: {str(e)}")
    print("Posibles soluciones:")
    print("1. Reducir el tamaño del batch")
    print("2. Usar float32 en lugar de float64")
    print("3. Verificar dimensiones de entrada")

Entrenando:  33%|███▎      | 10/30 [00:00<00:00, 21.04it/s]

Epoch 5, Loss: 0.2974
Epoch 10, Loss: 0.2470

Entrenando:  63%|██████▎   | 19/30 [00:00<00:00, 24.28it/s]

Epoch 15, Loss: 0.1963
Epoch 20, Loss: 0.1481

Entrenando: 100%|██████████| 30/30 [00:01<00:00, 22.40it/s]

Epoch 25, Loss: 0.1392
Epoch 30, Loss: 0.1439

In [11]:
# Change to eval mode
model.eval()
batch_size = 100  

# Use torch.no_grad() during inference (evaluation) to reduce memory usage and speed up computations by skipping gradient tracking
with torch.no_grad():
    correct_preds = 0
    total_preds = 0
    
    # Batch processing for evaluation
    for i in tqdm(range(0, len(X_test_tensor), batch_size), desc="Evaluando"):
        batch_X = X_test_tensor[i:i + batch_size]
        batch_y = y_test_tensor[i:i + batch_size]
        
        # Predictions as probabilities
        batch_output = model(batch_X)
        
        # Predicciones as classes
        batch_preds = (batch_output > 0.5).float()
        
        # Count to compute accuracy
        correct_preds += (batch_preds == batch_y).sum().item()
        total_preds += batch_y.size(0)

    # Accuracy calculation
    pt_accuracy = correct_preds / total_preds
    print(f'Accuracy: {pt_accuracy:.4f}')

Evaluando: 100%|██████████| 50/50 [00:00<00:00, 10841.36it/s]

Accuracy: 0.9440

In [12]:
# I do not run a cross-validation for the PyTorch model because it is very slow
# Save the results

model_name = "Pytorch"
n_repeats = 5

# Create DataFrame in one step
results_pt = pd.DataFrame({
    'model': [model_name] * n_repeats,
    'kf': [0] * n_repeats, 
    'Accuracy': [pt_accuracy] * n_repeats
})

print(results_pt)

results=results.append(results_pt, ignore_index=True)

     model  kf  Accuracy
0  Pytorch   0     0.944
1  Pytorch   0     0.944
2  Pytorch   0     0.944
3  Pytorch   0     0.944
4  Pytorch   0     0.944

/var/folders/gm/dmfb8b7n71jgq4nczfq076s40000gn/T/ipykernel_6716/3957595904.py:16: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  results=results.append(results_pt, ignore_index=True)

### Comparison

In [13]:
results.groupby('model').agg({'Accuracy':['mean','std']}).sort_values(by=('Accuracy', 'mean'),ascending=False)

                  Accuracy
                      mean       std
model
GradientBoostingC  0.98784  0.001307
Tensorflow         0.97688  0.008339
Pytorch            0.94400  0.000000

### Model hiperparameter tunning and model training

In [14]:
mdc = GridSearchCV(GradientBoostingClassifier(),
    param_grid={"n_estimators": np.linspace(50,200,10).astype('int'),  
                "max_depth": np.linspace(1,10,5).astype('int')},
    n_jobs=8) 
mdc.fit(X, y)
mdc.best_params_ # {'max_depth': 5, 'n_estimators': 100}

# Save the model
import joblib
joblib.dump(mdc.best_estimator_, 'gbc_best_model.pkl')
# Load the model
loaded_model = joblib.load('gbc_best_model.pkl')

In [15]:
tuner = RandomSearch(build_model, objective='val_accuracy', max_trials=10, executions_per_trial=1, directory='tuner_dir')
tuner.search(X, y, epochs=30, validation_split=0.2, batch_size=32)
best_hps = tuner.get_best_hyperparameters(num_trials=1)[0]

print(f"Best TensorFlow Model: units={best_hps.get('units')}, learning_rate={best_hps.get('learning_rate')}")

# Save the model
best_model.save('tf_best_model.keras')
# Load the model
loaded_model = keras.models.load_model('tf_best_model.keras')

Reloading Tuner from tuner_dir/untitled_project/tuner0.json
Best TensorFlow Model: units=128, learning_rate=0.001

In [16]:
# Tensors
X_tensor = safe_to_tensor(X.values.astype(np.float32))
y_tensor = torch.tensor(y.values.astype(np.float32)).unsqueeze(1)


try:
    model.train()
    for epoch in tqdm(range(30), desc="Entrenando"):
        optimizer.zero_grad()
        
        # Entrenamiento por lotes (batches)
        for i in range(0, len(X_train_tensor), batch_size):
            batch_X = X_tensor[i:i + batch_size]
            batch_y = y_tensor[i:i + batch_size]

            # Forward pass por lote
            outputs = model(batch_X)
            
            # Verificación de formas
            if outputs.shape != batch_y.shape:
                print(f"Error: outputs shape {outputs.shape} != y shape {batch_y.shape}")
                break

            loss = criterion(outputs, batch_y)
            
            # Backpropagation con manejo de gradientes
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)  # Evita gradientes explosivos
            optimizer.step()
        
        if (epoch + 1) % 5 == 0:
            print(f'Epoch {epoch + 1}, Loss: {loss.item():.4f}')
except RuntimeError as e:
    print(f"Error durante el entrenamiento: {str(e)}")
    print("Posibles soluciones:")
    print("1. Reducir el tamaño del batch")
    print("2. Usar float32 en lugar de float64")
    print("3. Verificar dimensiones de entrada")

#Save model
torch.save(model.state_dict(), 'pytorch_best_model.pth')
#Load model
model = BinaryClassifier(input_dim=X_train.shape[1])
model.load_state_dict(torch.load('pytorch_best_model.pth'))

Entrenando:  30%|███       | 9/30 [00:00<00:00, 21.66it/s]

Epoch 5, Loss: 0.1535
Epoch 10, Loss: 0.1544

Entrenando:  60%|██████    | 18/30 [00:00<00:00, 24.27it/s]

Epoch 15, Loss: 0.1569
Epoch 20, Loss: 0.0854

Entrenando:  90%|█████████ | 27/30 [00:01<00:00, 24.27it/s]

Epoch 25, Loss: 0.0926

Entrenando: 100%|██████████| 30/30 [00:01<00:00, 22.94it/s]

Epoch 30, Loss: 0.0702